const mangas=[
 {title:'Frieren',genre:'fantasy',label:'FANTASIA',chapters:'Cap. 132',rating:'4.9',img:'https://images.unsplash.com/photo-1541560052-77ec1bbc09f7?auto=format&fit=crop&w=600&q=85'},
 {title:'Blue Period',genre:'drama',label:'DRAMA',chapters:'Cap. 68',rating:'4.8',img:'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=600&q=85'},
 {title:'Dandadan',genre:'action',label:'AÇÃO',chapters:'Cap. 155',rating:'4.9',img:'https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=600&q=85'},
 {title:'Kimi ni Todoke',genre:'romance',label:'ROMANCE',chapters:'Cap. 128',rating:'4.7',img:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=85'},
 {title:'Kaiju No. 8',genre:'action',label:'AÇÃO',chapters:'Cap. 110',rating:'4.8',img:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=85'},
 {title:'A Sign of Affection',genre:'romance',label:'ROMANCE',chapters:'Cap. 52',rating:'4.9',img:'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=600&q=85'},
 {title:'One Piece',genre:'action',label:'AVENTURA',chapters:'Cap. 1148',rating:'4.9',img:'https://images.unsplash.com/photo-1534791547706-7bcb7856ebf7?auto=format&fit=crop&w=600&q=85'},
 {title:'Oshi no Ko',genre:'drama',label:'DRAMA',chapters:'Cap. 166',rating:'4.8',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=85'}
];
let currentFilter='all', visible=8, favorites=JSON.parse(localStorage.getItem('manganana-favs')||'[]');
const grid=document.querySelector('#mangaGrid');
function render(){const q=document.querySelector('#search').value.toLowerCase();const list=mangas.filter(m=>(currentFilter==='all'||m.genre===currentFilter)&&m.title.toLowerCase().includes(q)).slice(0,visible);grid.innerHTML=list.map((m,i)=>`<article class="manga-card" data-title="${m.title}"><div class="cover"><img loading="lazy" src="${m.img}" alt="Capa de ${m.title}"><button class="heart ${favorites.includes(m.title)?'liked':''}" data-fav="${m.title}">${favorites.includes(m.title)?'♥':'♡'}</button><div class="cover-info"><small>${m.label}</small><strong>${m.title}</strong></div></div><div class="card-meta"><span>${m.chapters}</span><span class="rating">★ ${m.rating}</span></div></article>`).join('');document.querySelector('#favCount').textContent=favorites.length;document.querySelector('#loadMore').style.display=visible>=mangas.length?'none':'inline-block';document.querySelector('#apiStatus').textContent='Catálogo sincronizado • fonte: MangaDex API';}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function openManga(title){const m=mangas.find(x=>x.title===title);document.querySelector('#modalContent').innerHTML=`<span class="section-kicker">${m.label}</span><h2>${m.title}</h2><p>Uma nova leitura espera por você. Acompanhe os capítulos em português, salve nos favoritos e continue de onde parou.</p><p><b>${m.chapters}</b> &nbsp; • &nbsp; ★ ${m.rating} &nbsp; • &nbsp; Atualizado hoje</p><button class="primary-btn" onclick="toast('Leitor em breve: capítulo aberto!');document.querySelector('#modal').classList.remove('open')">Ler capítulo →</button>`;document.querySelector('#modal').classList.add('open')}
grid.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const title=fav.dataset.fav;favorites=favorites.includes(title)?favorites.filter(x=>x!==title):[...favorites,title];localStorage.setItem('manganana-favs',JSON.stringify(favorites));toast(favorites.includes(title)?'Adicionado aos favoritos ♥':'Removido dos favoritos');render();return}const card=e.target.closest('.manga-card');if(card)openManga(card.dataset.title)});
document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));
document.querySelectorAll('.genre-card').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.genre;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===currentFilter));render()}));
document.querySelector('#search').addEventListener('input',render);document.querySelector('#loadMore').addEventListener('click',()=>{visible+=4;render()});document.querySelector('#closeModal').addEventListener('click',()=>document.querySelector('#modal').classList.remove('open'));document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')});document.querySelector('#filterBtn').addEventListener('click',()=>document.querySelector('#filters').classList.toggle('open'));document.querySelector('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('manganana-light',document.body.classList.contains('light'))});document.querySelector('#randomBtn').addEventListener('click',()=>openManga(mangas[Math.floor(Math.random()*mangas.length)].title));document.querySelector('#newsletter').addEventListener('submit',e=>{e.preventDefault();toast('Inscrição confirmada. Obrigado!');e.target.reset()});if(localStorage.getItem('manganana-light')==='true')document.body.classList.add('light');render();
window.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('#modal').classList.remove('open')});
// Estrutura pronta para integração real: MangaDex permite buscar obras por /manga?availableTranslatedLanguage[]=pt-br.
// Em produção, use um backend proxy para cache, CORS e filtragem de conteúdo/licenciamento.
(async()=>{try{const r=await fetch('https://api.mangadex.org/manga?limit=1&availableTranslatedLanguage[]=pt-br&contentRating[]=safe');if(r.ok)document.querySelector('#apiStatus').textContent='Catálogo conectado • MangaDex em português'}catch(e){document.querySelector('#apiStatus').textContent='Modo demonstração • API disponível no backend'}})();
